### ISSUE TITLE
Flash Library

### ISSUE THREAD

**Issue by JVKran** [jandrassy/SDUnRF5#1]
Hi Jandrassy!

I'm currently working on a project that involves directly writing firmware from an SD-card into Flash memory of the nRF52832. That's when a colleague of mine showed my your repository.

Unfortunately I can't seem to find the Flash Library you used. Do mind sharing it with me?

Kind regards,

Jochem

**Comment by JAndrassy** [comment]
the InternalStorage object created by my ArduinoOTA library can store and then apply firmware on nRF52832
https://github.com/jandrassy/ArduinoOTA/blob/master/README.md
